### ISSUE TITLE
Where is "hook_softmax"?

### ISSUE THREAD

**Issue by WeiYu021** [RenYurui/Neural-Texture-Extraction-Distribution#13]
我看到代码中是通过hook_softmax来实现注意力图的：

extraction_distribution_trainer.py中的
attn_image = attn2image(info['hook_softmax'], info['semantic_distribution'], input_image)

但是并没有在model中找到这个键位，请问它在哪里呢？感谢~

**Comment by RenYurui** [comment]
Please find it here:    
https://github.com/RenYurui/Neural-Texture-Extraction-Distribution/blob/b2e70b77d4b92da352ae6404f72ddd711c2a668d/generators/base_function.py#L19
In recoder['extraction_softmax'];
