### ISSUE TITLE
i only found 'extraction_softmax' in the code.  Are they the same?

### ISSUE THREAD

**Issue by ok-f1ne** [RenYurui/Neural-Texture-Extraction-Distribution#14]
https://github.com/RenYurui/Neural-Texture-Extraction-Distribution/blob/6e3f0e94c4b6a14ceafa4f8d82950e6b4674a0b3/trainers/extraction_distribution_trainer.py#L188

**Comment by WeiYu021** [comment]
yes, just replace it with extraction.

**Comment by ok-f1ne** [comment]
> yes, just replace it with extraction.

thx!
