### ISSUE TITLE
TypeError: MaskRCNN: __init__() got an unexpected keyword argument 'bbox_roi_extractor'

### ISSUE THREAD

**Issue by pfeducode** [RenYurui/Neural-Texture-Extraction-Distribution#19]
Why did I get this mistake? Can you give me some advice？
![2022-10-15_16-11](https://user-images.githubusercontent.com/100210045/197443287-cca52514-a3bd-4ae7-a6a7-95f868c744e4.png)

**Comment by pfeducode** [comment]
I seem to have downloaded the wrong file, which has now been resolved

**Comment by linziqu** [comment]
Hi, I have met the same problem. How did you solve it？
Thanks a lot!

**Comment by pfeducode** [comment]
> 嗨，我遇到了同样的问题。你是怎么解决的？ 非常感谢！

You should use openpose to obtain key points
