### ISSUE TITLE
Head Transfer

### ISSUE THREAD

**Issue by Deepak2405** [RenYurui/Neural-Texture-Extraction-Distribution#22]
Hi, Thank you for your amazing work. Could you explain how could I generate head-transfer?

**Comment by Taylor-Pan** [comment]
Specify Euler angle

**Comment by Deepak2405** [comment]
Thank you, where exactly should I mention that and where all the changes I should make in the code?

**Comment by Taylor-Pan** [comment]
In this project, I think you should change the head landmark to change the head angle.How to make changes in the code requires you to carefully review the code
