### ISSUE TITLE
Incomplete pose file

### ISSUE THREAD

**Issue by moonlight703** [RenYurui/Neural-Texture-Extraction-Distribution#3]
Hi Ren Yurui,

Thanks for your work.

I encountered an error when training the model. neural-Texture-Extraction-Distribution main/dataset/deepfashion/pose/WOMEN/Blouses_Shirts/id_00001612/02_4_full.txt not found. I checked train_pairs.txt and found it exists, but it does not exist in the pose file. Also, I found that the number of images in the img file is  larger than the number of files in the pose file. So I would like to ask if the pose file you gave is incomplete. If so, can you release the full pose file?

Thanks!

**Comment by RenYurui** [comment]
Hi! 
The pose file has been updated, please check the new files!
Yurui

**Comment by wzic** [comment]
another error:
FileNotFoundError: ../../dataset/deepfashion_nted/pose/MEN/Tees_Tanks/id_00001774/23_6_flat.txt not found.
